# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: git@github.com:finitelabs/control4-driver-template.git
project_name: control4-mqtt
project_description: Control4 driver for MQTT broker connectivity
github_org: finitelabs
distributions: drivercentral oss
readme_driver_slug: mqtt_broker
readme_build: oss
primary_color: "#660066"
vendor_modules: json deferred drivers-common-public xml